name: BlockKeepAlive
version: @version@-@apiversion@
description: An empty plugin for Spigot with Maven
authors: [ DartPower, UnknownContributorName ]
website: https://github.com/dptmc/BlockKeepAlive
main: io.dpteam.BlockKeepAlive.Main
depend: [ProtocolLib]